name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  date_job:
    runs-on: ubuntu-22.04
    steps:
      - run: date
  
  ls_job:
    runs-on: ubuntu-22.04
    steps:
      - run: ls -l
