name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]    
    types: [opened, synchronize]

env:
  DEPLOY: ${{ !contains(github.event.head_commit.message, '#skip') && github.event_name == 'push' }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run eslint
      - run: npm run build
      - run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Trigger deployment
        if: ${{ env.DEPLOY == 'true' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: report success
        if: ${{ env.DEPLOY == 'true' && success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          avatarUrl: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5slXgDa1VWsWD1TCM8PETFCQDLCzGclh2qw&s
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: report failure
        if: ${{ env.DEPLOY == 'true' && failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          avatarUrl: https://www.pngmart.com/files/11/Rickrolling-PNG-Pic.png
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
      if: ${{ github.env.DEPLOY == 'true' }}
      runs-on: ubuntu-20.04
      needs: [simple_deployment_pipeline]
      steps:
        - uses: actions/checkout@v4
        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@1.69.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WITH_V: true
            DEFAULT_BUMP: patch
